### PR TITLE
Compose 1.6

### LINKED ISSUE #197: iOS like gesture navigation back UI glitch
When navigating back with ios style navigation gesture previous entry is rendered briefly because of exit animation in

https://github.com/Tlaster/PreCompose/assets/32630888/dca991ac-fe89-4c20-8dfc-142530568e69

/// do not mind jumping list it is some other issue with recomposition.

https://github.com/Tlaster/PreCompose/assets/32630888/d4d2cb7b-4b68-4455-bffd-b1c5ff860ecb

```kotlin
 AnimatedContent(
                        backStackEntry,
                        transitionSpec = {
                            if (prevWasSwiped) {
                                EnterTransition.None togetherWith ExitTransition.None
                            } else {
                                transitionSpec()
                            }
                        },
                        modifier = Modifier.zIndex(
                            if (isPrev) {
                                0f
                            } else {
                                1f
                            },
                        ),
                    ) {
                        SwipeItem(
                            dismissState = dismissState,
                            swipeProperties = actualSwipeProperties,
                            isPrev = isPrev,
                            isLast = !canGoBack,
                        ) {
                            NavHostContent(composeStateHolder, it)
                        }
                    }
                    
  //Sugestion

if (prevWasSwiped) {
                        SwipeItem(
                            dismissState = dismissState,
                            swipeProperties = actualSwipeProperties,
                            isPrev = isPrev,
                            isLast = !canGoBack,
                        ) {
                            NavHostContent(composeStateHolder, backStackEntry)
                        }
                    } else {
                        AnimatedContent(
                            backStackEntry,
                            transitionSpec = {
                                transitionSpec()
                            },
                            modifier = Modifier.zIndex(
                                if (isPrev) {
                                    0f
                                } else {
                                    1f
                                },
                            ),
                        ) {
                            SwipeItem(
                                dismissState = dismissState,
                                swipeProperties = actualSwipeProperties,
                                isPrev = isPrev,
                                isLast = !canGoBack,
                            ) {
                                NavHostContent(composeStateHolder, it)
                            }
                        }
                    }`

### PR DESCRIPTION
**Pull request by Tlaster**
fix #197, #223

### CODE REVIEW

**Comment by Tlaster** [comment]
> Hi,
> 
> Could you please tag a new version with a bump of Compose Plugin to rc02 ("upgrade compose to 1.6.0-rc02")?
> 
> I encountered an issue with the latest tag (beta02) related to this problem: [JetBrains/compose-multiplatform#4277](https://github.com/JetBrains/compose-multiplatform/issues/4277)
> 
> Thanks a lot,

PreCompose also have the same issue, waiting koin to upgrade.

**Comment by armond1978** [comment]
@Tlaster Is there any GitHub issue filed for Koin or any active PR that we can track the progress on that side?

**Comment by Tlaster** [comment]
> @Tlaster Is there any GitHub issue filed for Koin or any active PR that we can track the progress on that side?

Not yet, I think koin team has their own release plan.

**Comment by c4software** [comment]
Hi,

Also, the latest tag seems have an issue with the go back implementation :

With beta02 I have crash when I do the go back gesture
```
FATAL EXCEPTION: main
Process: com.pmw.config.client, PID: 10702
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Ljava/lang/Object;)V in class Landroidx/compose/animation/core/SeekableTransitionState; or its super classes (declaration of 'androidx.compose.animation.core.SeekableTransitionState' appears in /data/app/~~sz-R3_GfIP15OPg9lg5JTQ==/com.arcure.bxt5.config.client-l2AjiPOx5V5OqMDXusRqjw==/base.apk)
at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt:182)
```

No problem with the previous version.

**Comment by Tlaster** [comment]
> Hi,
> 
> Also, the latest tag seems have an issue with the go back implementation :
> 
> With beta02 I have crash when I do the go back gesture
> 
> ```
> FATAL EXCEPTION: main
> Process: com.pmw.config.client, PID: 10702
> java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Ljava/lang/Object;)V in class Landroidx/compose/animation/core/SeekableTransitionState; or its super classes (declaration of 'androidx.compose.animation.core.SeekableTransitionState' appears in /data/app/~~sz-R3_GfIP15OPg9lg5JTQ==/com.arcure.bxt5.config.client-l2AjiPOx5V5OqMDXusRqjw==/base.apk)
> at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt:182)
> ```
> 
> No problem with the previous version.

Can you check if you have compose material 1.6.0 as dependency?

**Comment by c4software** [comment]
> > Hi,
> > Also, the latest tag seems have an issue with the go back implementation :
> > With beta02 I have crash when I do the go back gesture
> > ```
> > FATAL EXCEPTION: main
> > Process: com.pmw.config.client, PID: 10702
> > java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Ljava/lang/Object;)V in class Landroidx/compose/animation/core/SeekableTransitionState; or its super classes (declaration of 'androidx.compose.animation.core.SeekableTransitionState' appears in /data/app/~~sz-R3_GfIP15OPg9lg5JTQ==/com.arcure.bxt5.config.client-l2AjiPOx5V5OqMDXusRqjw==/base.apk)
> > at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt:182)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No problem with the previous version.
> 
> Can you check if you have compose material 1.6.0 as dependency?

Juste `Compose.Material3` :

Capture d’écran 2024-02-20 à 16 01 41

**Comment by Tlaster** [comment]
> > > Hi,
> > > Also, the latest tag seems have an issue with the go back implementation :
> > > With beta02 I have crash when I do the go back gesture
> > > ```
> > > FATAL EXCEPTION: main
> > > Process: com.pmw.config.client, PID: 10702
> > > java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Ljava/lang/Object;)V in class Landroidx/compose/animation/core/SeekableTransitionState; or its super classes (declaration of 'androidx.compose.animation.core.SeekableTransitionState' appears in /data/app/~~sz-R3_GfIP15OPg9lg5JTQ==/com.arcure.bxt5.config.client-l2AjiPOx5V5OqMDXusRqjw==/base.apk)
> > > at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt:182)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > No problem with the previous version.
> > 
> > 
> > Can you check if you have compose material 1.6.0 as dependency?
> 
> Juste `Compose.Material3` :
> 
> Capture d’écran 2024-02-20 à 16 01 41

Can you check if add compose material works for you?

**Comment by c4software** [comment]
Same error `implementation(compose.material)`

**Comment by c4software** [comment]
Nop, same error with `implementation("androidx.compose.material:material:1.6.1")` in `androidMain.dependencies`

**Comment by c4software** [comment]
@Tlaster Its look like the `compose.animation` is resolved in `animation-core-android-1.7.0-alpha01`,  who does not have this signature method, but this one :

```kt
 class SeekableTransitionState<S>(
    initialState: S
) : TransitionState<S>() { /* […] */ }
```

**Comment by Tlaster** [comment]
> @Tlaster Its look like the `compose.animation` is resolved in `animation-core-android-1.7.0-alpha01`, who does not have this signature method, but this one :
> 
> ```kotlin
>  class SeekableTransitionState<S>(
>     initialState: S
> ) : TransitionState<S>() { /* […] */ }
> ```
> 
> Maybe you could tag a updated pre-release version based on your latest addition (ComposePlugin-rc02) ?

Before I can push a new release based on compose 1.6.0-rc02 (which I cannot do right now since koin is still not updating its compose dependency version), can you provide a sample that can reproduce this issue? It works fine here.

**Comment by c4software** [comment]
> > @Tlaster Its look like the `compose.animation` is resolved in `animation-core-android-1.7.0-alpha01`, who does not have this signature method, but this one :
> > 
> > ```kotlin
> >  class SeekableTransitionState<S>(
> >     initialState: S
> > ) : TransitionState<S>() { /* […] */ }
> > ```
> > 
> > Maybe you could tag a updated pre-release version based on your latest addition (ComposePlugin-rc02) ?
> 
> Before I can push a new release based on compose 1.6.0-rc02 (which I cannot do right now since koin is still not updating its compose dependency version), can you provide a sample that can reproduce this issue? It works fine here.

Hi try your branch too to confirm if it's my code or an incompatibility between versions. 

And I confirm it's because the precompose-beta02 code is on the beta02 tag of the ComposePlugin, but my code is based on the rc02 ComposePlugin. I can produce a sample code but IDK If it's really useful. 

Since the problem with koin is only with iOS, Its not a really a problem for me (my app is not in production right now). But ok I will wait 👍

**Comment by c4software** [comment]
> > @Tlaster Is there any GitHub issue filed for Koin or any active PR that we can track the progress on that side?
> 
> Not yet, I think koin team has their own release plan.

It's happening (soon) https://github.com/InsertKoinIO/koin/issues/1634#issuecomment-1960959984

**Comment by c4software** [comment]
> > @Tlaster Its look like the `compose.animation` is resolved in `animation-core-android-1.7.0-alpha01`, who does not have this signature method, but this one :
> > ```kotlin
> >  class SeekableTransitionState<S>(
> >     initialState: S
> > ) : TransitionState<S>() { /* […] */ }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe you could tag a updated pre-release version based on your latest addition (ComposePlugin-rc02) ?
> 
> Before I can push a new release based on compose 1.6.0-rc02 (which I cannot do right now since koin is still not updating its compose dependency version), can you provide a sample that can reproduce this issue? It works fine here.

Hi, 

I still have the issue with the latest rc01 version.

```
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Ljava/lang/Object;)V in class Landroidx/compose/animation/core/SeekableTransitionState; or its super classes (declaration of 'androidx.compose.animation.core.SeekableTransitionState' appears in …
```

**Comment by c4software** [comment]
To complete my comment :

I also have a strange method resolution, in the documentation of SeekableTransitionState, we found this :

https://developer.android.com/reference/kotlin/androidx/compose/animation/core/SeekableTransitionState

`<S : Any?> SeekableTransitionState(initialState: S)`

But in my Android Studio, I have :

import androidx.compose.animation.core.SeekableTransitionState

`class SeekableTransitionState<S>(
    initialState: S,
    override val targetState: S
) : TransitionState<S>() {`

And, when my application run, its obviously crash :

`java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Ljava/lang/Object;)V in class Landroidx/compose/animation/core/SeekableTransitionState; or its super classes (declaration of 'androidx.compose.animation.core.SeekableTransitionState' appears in …`

It's seems related to the 1.6.0 upgrade, but not sure why …

**Comment by Tlaster** [comment]
> To complete my comment :
> 
> I also have a strange method resolution, in the documentation of SeekableTransitionState, we found this :
> 
> https://developer.android.com/reference/kotlin/androidx/compose/animation/core/SeekableTransitionState
> 
> `<S : Any?> SeekableTransitionState(initialState: S)`
> 
> But in my Android Studio, I have :
> 
> import androidx.compose.animation.core.SeekableTransitionState
> 
> `class SeekableTransitionState<S>( initialState: S, override val targetState: S ) : TransitionState<S>() {`
> 
> And, when my application run, its obviously crash :
> 
> `java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Ljava/lang/Object;)V in class Landroidx/compose/animation/core/SeekableTransitionState; or its super classes (declaration of 'androidx.compose.animation.core.SeekableTransitionState' appears in …`
> 
> It's seems related to the 1.6.0 upgrade, but not sure why …

Which version of compose you're using for the android project?

**Comment by Tlaster** [comment]
@c4software I think accompanist might be the issue, [0.35.0-alpha](https://github.com/google/accompanist/releases/tag/v0.35.0-alpha) is targeting compose 1.7, can you try version 0.34.0?

**Comment by c4software** [comment]
Oh yes ! Thats the root cause ! Thanks a lot.

**Comment by c4software** [comment]
Hi,

With the addition of `Predictive Back` is it possible to disable it for one scene in particular (it's works great, but in one of my screen the transition is not smooth) ?

**Comment by Tlaster** [comment]
> Hi,
> 
> With the addition of `Predictive Back` is it possible to disable it for one scene in particular (it's works great, but in one of my screen the transition is not smooth) ?

It is, you can just have a `BackHandler` in your screen and navigate back manually, the predictive back will be disable completely.
Note: 1.6.0-rc04 have issue with `BackHandler` and predictive back, 1.6.0-rc05 will fix this.

**Pull request merged**
