### PR TITLE
Swipe back navigation

### PR DESCRIPTION
**Pull request by alexzhirkevich**
Hey again.

UIKIt navigation with compose is too laggy now so i just added iOS-like compose swipe back navigation.

### CODE REVIEW

**Comment by Tlaster** [comment]
Thanks for the PR!
Do you run the `./gradlew spotlessApply` to apply the code style?

**Comment by alexzhirkevich** [comment]
Done. May be it will also be good to have an ability to set swipe properteis for each route separatly like nav transition?

**Comment by alexzhirkevich** [comment]
@Tlaster, I guess PR is ready for review

**Comment by Joehzd** [comment]
How can I use the new features?

**Review by Tlaster — APPROVED** [review]
Thanks! LGTM!

**Pull request merged**
