### PR TITLE
Remove appcompat dependency

### PR DESCRIPTION
**Pull request by martinbonnin**
Looks like appcompat is not needed? 

More context in https://github.com/paug/AndroidMakersApp/pull/299

### CODE REVIEW

**Comment by Tlaster** [comment]
Seems like we also need to update the sample code as well in order to pass the ci build.

**Comment by martinbonnin** [comment]
> Seems like we also need to update the sample code as well in order to pass the ci build.
I just pushed https://github.com/Tlaster/PreCompose/pull/316/commits/ec704b51c40c2f5337ad4393179f39645ba5f9b5

**Comment by cbeyls** [comment]
Actually the sample doesn't need AppCompat either.
`MainActivity` doesn't extend `AppCompatActivity` so it shouldn't use an `AppCompat` theme in the Manifest. The theme should be changed to a system theme instead.

**Comment by martinbonnin** [comment]
> Actually the sample doesn't need AppCompat either.
> MainActivity doesn't extend AppCompatActivity so it shouldn't use an AppCompat theme in the Manifest. The theme should be changed to a system theme instead.

Sounds good to me. I'll let the maintainers decide how they want to handle this. I have enabled maintainers edit. Feel free to push to this branch and/or create a follow up PR

**Review by Tlaster — APPROVED** [review]

**Pull request merged**
