### PR TITLE
Adding wasm-js target to precompose

### PR DESCRIPTION
**Pull request by bashor**
It adds wasm-js only to the precompose subproject. Anyway, it would be nice if you could accept the PR and publish an updated version to Maven Central.

### CODE REVIEW

**Comment by Tlaster** [comment]
Thanks for the PR!
wasmjs target has already been added in #251 with 1.6.0-rc5 release, and soon will be merged into master and have a stable release.

**Comment by bashor** [comment]
@Tlaster, I'm wondering how soon? Maybe you can publish some prerelease from that (`compose-1.6`) branch sooner?

**Comment by Tlaster** [comment]
> @Tlaster, I'm wondering how soon? Maybe you can publish some prerelease from that (`compose-1.6`) branch sooner?

Maybe next week I will release a stable version, and there's also prerelease version from `compose-1.6` branch, the latest version is `1.6.0-rc05`

**Comment by bashor** [comment]
@Tlaster oh you meant `1.6.0-rc05` for recompose, I've confused it with a compose version. Thanks, that works!

**Pull request closed without merging**
